# Generated by Django 4.2.7 on 2023-11-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_category_listing_image_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
