# Generated by Django 4.2.7 on 2023-11-25 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_watchlist_delete_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='WatchList',
        ),
        migrations.AddField(
            model_name='listing',
            name='WatchList',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_watch', to=settings.AUTH_USER_MODEL),
        ),
    ]
